apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: outils
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: 6.6.3          # épingle une version (mets à jour si besoin)
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    service:
      type: NodePort
      port: 9898
      nodePort: 30989
    ui:
      color: "#3455ff"